name: Web

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          repository: BrandenXia/n2web
      - uses: actions/checkout@v6
        with:
          path: ./notes
          fetch-depth: 0
      - name: Restore timestamps
        uses: chetan/git-restore-mtime-action@v2
        with:
          working-directory: ./notes
      - name: Restore build cache
        id: cache
        uses: actions/cache/restore@v5
        with:
          path: .build-cache.tar.gz
          key: notes-build-cache-${{ github.run_id }}
          restore-keys: |
            notes-build-cache-
      - name: Extract cache
        if: steps.cache.outputs.cache-hit == 'true'
        run: |
          tar -xzf .build-cache.tar.gz
          echo "Cache extracted"
      - uses: oven-sh/setup-bun@v2
      - uses: typst-community/setup-typst@v5
      - name: Build
        run: make
      - name: Upload static files as artifact
        id: deployment
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist/
      - name: Compress cache
        run: |
          tar -czf .build-cache.tar.gz dist/
          echo "Cache compressed"
      - name: Save build cache
        id: cache-save
        uses: actions/cache/save@v5
        with:
          path: .build-cache.tar.gz
          key: notes-build-cache-${{ github.run_id }}

  deploy:
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
